server:
  port: 9096

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: zwz_123
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    #password: your-password (如有密码)
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenzhi.leetcode_service.entity
  config-location: classpath:mybatis-config.xml # 指定 mybatis-config.xml 文件的位置
#  monitor:
#    slow-sql-threshold: 500   # 慢SQL阈值
#    enable-param-log: true     # 是否记录参数明细
#    max-param-length: 200      # 参数值最大显示长度
# 日志配置（可选）
logging:
  level:
    com.wenzhi.leetcode_service.dao: DEBUG
redisson:
  config: |  # 直接配置 Redisson 参数
    singleServerConfig:
      timeout: 5000  # 单位毫秒
      connectionMinimumIdleSize: 10  # 最小空闲连接
      connectionPoolSize: 64        # 最大连接数
      idleConnectionTimeout: 10000
      address: "redis://${spring.redis.host}:${spring.redis.port}"
      database: ${spring.redis.database}
      #password: ${spring.redis.password}
    codec: !<org.redisson.codec.JsonJacksonCodec> {}  # 使用 JSON 序列化
# 集群模式
#redisson:
#  config: |
#    clusterServersConfig:
#      nodeAddresses:
#        - "redis://192.168.1.101:6379"
#        - "redis://192.168.1.102:6379"
#        - "redis://192.168.1.103:6379"
#      password: "your-cluster-password"
#      scanInterval: 5000  # 集群状态检查间隔
#    codec: !<org.redisson.codec.MsgPackJacksonCodec> {}  # 高性能序列化

# @Scheduled注解配置
task:
  fixed:
    rate: 5000
  cron: 0 0/30 * * * ?
  cleanup:
    cron: "0 0 3 * * ?"  # 每天凌晨3点执行
  report:
      interval: 3600000     # 每小时执行一次（单位：毫秒）
##############定时日志清理配资#############
notification:
  webhook-url: http://localhost:${server.port}/alert
  retain-log-days: 30