<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.wenzhi</groupId>
        <artifactId>spring-cloud-alibaba-wenzhi</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>leetcode-service</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Thymeleaf 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <!-- FreeMarker 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>
        <!-- Spring Validation 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-aop -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <!-- Spring Security (密码加密) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- JSON Processing API -->
        <dependency>
            <groupId>jakarta.json</groupId>
            <artifactId>jakarta.json-api</artifactId>
            <version>2.1.2</version>
        </dependency>
        <!-- JSON Processing 实现（Eclipse Parsson） -->
        <dependency>
            <groupId>org.eclipse.parsson</groupId>
            <artifactId>parsson</artifactId>
            <version>1.1.3</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
        </dependency>

        <!-- MyBatis Spring Boot Starter -->
        <!-- https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter -->
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>3.0.4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.5</version>
        </dependency>

        <!-- Redisson Starter -->
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.45.0</version>
        </dependency>
        <!-- 排除默认的 Lettuce/Jedis 避免冲突 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.lettuce</groupId>
                    <artifactId>lettuce-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>5.2.0</version>
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>io.netty</groupId>-->
<!--                    <artifactId>netty-common</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
        </dependency>

        <!-- 日志依赖（可选，解决 SLF4J 警告） 启动开始还是会警告 -->
<!--        <dependency>-->
<!--            <groupId>org.slf4j</groupId>-->
<!--            <artifactId>slf4j-simple</artifactId>-->
<!--            <version>2.0.17</version>-->
<!--        </dependency>-->

        <!-- JWT工具库（推荐jjwt） -->
        <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api -->
<!--        <dependency>-->
<!--            <groupId>io.jsonwebtoken</groupId>-->
<!--            <artifactId>jjwt-api</artifactId>-->
<!--            <version>0.12.6</version>-->
<!--        </dependency>-->
        <!-- https://mvnrepository.com/artifact/com.auth0/java-jwt 可选替代库（如java-jwt）-->
<!--        <dependency>-->
<!--            <groupId>com.auth0</groupId>-->
<!--            <artifactId>java-jwt</artifactId>-->
<!--            <version>4.5.0</version>-->
<!--        </dependency>-->

        <!-- 核心API接口（编译时依赖） -->
<!--        <dependency>-->
<!--            <groupId>io.jsonwebtoken</groupId>-->
<!--            <artifactId>jjwt-api</artifactId>-->
<!--            <version>0.12.6</version>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; 实现模块（运行时依赖） &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>io.jsonwebtoken</groupId>-->
<!--            <artifactId>jjwt-impl</artifactId>-->
<!--            <version>0.12.6</version>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; JSON序列化支持（运行时依赖） &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>io.jsonwebtoken</groupId>-->
<!--            <artifactId>jjwt-jackson</artifactId>-->
<!--            <version>0.12.6</version>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->

        <!-- 在NotificationService中添加重试机制 -->
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.hibernate.validator/hibernate-validator -->
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>8.0.2.Final</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.poi/poi -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.4.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.4.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.lionsoul/ip2region 2023年停止更新 https://github.com/lionsoul2014/ip2region -->
        <dependency>
            <groupId>org.lionsoul</groupId>
            <artifactId>ip2region</artifactId>
            <version>2.7.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/cn.hutool/hutool-all -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.8.36</version>
        </dependency>

<!--        &lt;!&ndash; shardingJDBC 核心依赖 &ndash;&gt;-->
<!--        &lt;!&ndash; 2022年停止更新 https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-jdbc-core-spring-boot-starter &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.apache.shardingsphere</groupId>-->
<!--            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>-->
<!--            <version>5.2.1</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.yaml</groupId>-->
<!--                    <artifactId>snakeyaml</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>me.ahoo.cosid</groupId>-->
<!--                    <artifactId>cosid-core</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; 啃爹的版本冲突 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.yaml</groupId>-->
<!--            <artifactId>snakeyaml</artifactId>-->
<!--            &lt;!&ndash; <version>1.33</version> 2025年有在更新&ndash;&gt;-->
<!--            <version>2.4</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>me.ahoo.cosid</groupId>-->
<!--            <artifactId>cosid-core</artifactId>-->
<!--            &lt;!&ndash; <version>1.19.3</version> 2025年有在更新&ndash;&gt;-->
<!--            <version>2.12.3</version>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; XA 分布式事务 &ndash;&gt;-->
<!--        &lt;!&ndash; 这个2025还在更新的：5.5.2，https://mvnrepository.com/artifact/org.apache.shardingsphere/shardingsphere-transaction-xa-core &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.apache.shardingsphere</groupId>-->
<!--            <artifactId>shardingsphere-transaction-xa-core</artifactId>-->
<!--            &lt;!&ndash; <version>5.2.1</version>&ndash;&gt;-->
<!--            <version>5.5.2</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>com.atomikos</groupId>-->
<!--                    <artifactId>transactions-jdbc</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.atomikos</groupId>-->
<!--                    <artifactId>transactions-jta</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; 版本滞后了 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.atomikos</groupId>-->
<!--            <artifactId>transactions-jdbc</artifactId>-->
<!--            &lt;!&ndash;<version>5.0.8</version> 2020&ndash;&gt;-->
<!--            &lt;!&ndash; 2023年停止更新 &ndash;&gt;-->
<!--            <version>6.0.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.atomikos</groupId>-->
<!--            <artifactId>transactions-jta</artifactId>-->
<!--            &lt;!&ndash;<version>5.0.8</version> 2020&ndash;&gt;-->
<!--            &lt;!&ndash; 2023年停止更新 &ndash;&gt;-->
<!--            <version>6.0.0</version>-->
<!--        </dependency>-->
<!--&lt;!&ndash;        <dependency>&ndash;&gt;-->
<!--&lt;!&ndash;            <groupId>org.springframework.boot</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;            <artifactId>sprint-boot-starter</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;            <exclusions>&ndash;&gt;-->
<!--&lt;!&ndash;                <exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;                    <groupId>org.yaml</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                    <artifactId>snakeyaml</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                </exclusion>&ndash;&gt;-->
<!--&lt;!&ndash;            </exclusions>&ndash;&gt;-->
<!--&lt;!&ndash;        </dependency>&ndash;&gt;-->
<!--        &lt;!&ndash; 连接池依赖：不要用starter-druid,由于starter-druid会自动配置一个datasource，会和sharding的datasource产生冲突 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.alibaba</groupId>-->
<!--            <artifactId>druid</artifactId>-->
<!--&lt;!&ndash;            <version>1.2.20</version>&ndash;&gt;-->
<!--            &lt;!&ndash; 2024年 &ndash;&gt;-->
<!--            <version>1.2.24</version>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter</artifactId>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.yaml</groupId>-->
<!--                    <artifactId>snakeyaml</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-actuator</artifactId>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java</artifactId>
            <version>24.1</version>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <!-- 确保该类所在的模块被正确引入到项目中 -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.class</include>
                </includes>
            </resource>
            <!-- 确保 src/main/resources 目录下的文件被正确处理 -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
        <!-- 其他构建配置 -->
    </build>

</project>